//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int ID { get; set; }
        public int Trainee_id { get; set; }
        public int MD_id { get; set; }
        public int Proj_id { get; set; }
        public int IsApproved { get; set; }
        public string TeamName { get; set; }
        public int MTL_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
